export interface FactorResult { raw: number; normalized: number; details?: any }

export * from './opportunityQuality'
export * from './clientTrust'
export * from './paymentSafety'
export * from './estimatedProfit'
export * from './estimatedTime'
export * from './competition'
export * from './historicalWinRate'
export * from './learningEngineConfidence'
export * from './platformReputation'
export * from './executionComplexity'
export * from './urgency'
export * from './scamDetection'
export * from './previousClientBehaviour'
export * from './returnClientBonus'
export * from './portfolioMatch'
export * from './categoryExperience'
export * from './proposalMatchQuality'
export * from './pricingConfidence'
export * from './workerAvailability'
export * from './executionSuccessPrediction'
